### ISSUE TITLE
Update animated wave

### ISSUE THREAD

**Issue by vagechirkov** [TechLabs-Berlin/wt21-the-noise-enricher#16]
@giannamoth, I really like the animated wave! But in my opinion, it would be great to make it smoother. Do you think it is possible?

![image](https://user-images.githubusercontent.com/42982039/148661113-3b27d566-5a1d-419f-bb38-0eb4e07d1afb.png)

**Comment by giannamoth** [comment]
for smoother you mean the quality or the velocity? :)

**Comment by vagechirkov** [comment]
> for smoother you mean the quality or the velocity? :)

I mean the image quality, namely these 'jaggs'.

![image](https://user-images.githubusercontent.com/42982039/148691133-59287d94-f2ed-43d7-865a-5c056bff6686.png)

**Comment by giannamoth** [comment]
yeah, I can render a new video
