### ISSUE TITLE
ruuning ejs fail

### ISSUE THREAD

**Issue by giannamoth** [TechLabs-Berlin/wt21-the-noise-enricher#28]
![Cattura1](https://user-images.githubusercontent.com/79792034/150687732-c7f38fc1-fdd0-4917-8b15-5d2738660f73.PNG)
![Cattura2](https://user-images.githubusercontent.com/79792034/150687733-8b354ffa-db3b-48ff-b9fb-83b514537de2.PNG)
![Cattura3](https://user-images.githubusercontent.com/79792034/150687734-2bdaba8c-0c0e-4384-ae75-ed42d30d2a85.PNG)

those are the error messages that I get when attempting to run on my localhost the app.js

Any idea how to solve it?

**Comment by vagechirkov** [comment]
@giannamoth can I close this issue? :)

**Comment by giannamoth** [comment]
naturlisch :)
