### ISSUE TITLE
Clean up folder structure of python_app

### ISSUE THREAD

**Issue by christian-eismann** [TechLabs-Berlin/wt21-the-noise-enricher#36]
all trained models an weights should be saved in the python_app/models folder with with '_genre' suffix. training files should be in a separate folder

**Comment by vagechirkov** [comment]
@christian-eismann could you point out where you call noise enricher to generate a new audio file?

**Comment by vagechirkov** [comment]
I found it! This code, right?

```python

  path_to_input_file = '/home/christian/Documents/sound_classifier/test_sounds/witchfucker.wav'
  preprocess = preprocessor(path_to_input_file)

  input_arrays, minmax = preprocess.to_encoder()

  create_sound(input_arrays, minmax)



```

**Comment by christian-eismann** [comment]
yes, thats it. it runs on my local computer, maybe somewhere are hard coded paths or something. i will check that tomorrow. the script also produces several wave files of 3 seconds and not one file, i will fix that, too.

**Comment by vagechirkov** [comment]
> yes, thats it. it runs on my local computer, maybe somewhere are hard coded paths or something. i will check that tomorrow. the script also produces several wave files of 3 seconds and not one file, i will fix that, too.

I am now trying to connect it to Node.js. I will open PR if have some progress with this
