### ISSUE TITLE
Selecting different sound styles for autoencoder

### ISSUE THREAD

**Issue by christian-eismann** [TechLabs-Berlin/wt21-the-noise-enricher#42]
- add 'genre'-parameter to VAE class in enricher_models.py
- pass the genre parameter from create_sound.py file
- store all weights and parameters with "_genre" in filename in the folder python_app/models

**Comment by vagechirkov** [comment]
@christian-eismann I have deployed the last update, do you think the produced sound is correct? 
https://noise-enricher.herokuapp.com/generate

**Comment by christian-eismann** [comment]
@vagechirkov i guess the sound is "correct" ;) we only need to implement the choice of a certain genre aka using different encoder models. the parameter is already implemented in the model definition itself and `sound_generator.py`: so one can call the function with `generate_sound(..., genre='blues')` currently we can provide `['blues', 'hiphop', 'metal]` maybe you just have to update the `call_generate_audio.py` with another `sys.argv` parameter representing one of the three genres.

@giannamoth can we use the sliders on the left or the buttons in the middle to select the genre? the buttons should return one of the strings in the list above.

**Comment by vagechirkov** [comment]
> @vagechirkov i guess the sound is "correct" ;) we only need to implement the choice of a certain genre aka using different encoder models. the parameter is already implemented in the model definition itself and `sound_generator.py`: so one can call the function with `generate_sound(..., genre='blues')` currently we can provide `['blues', 'hiphop', 'metal]` maybe you just have to update the `call_generate_audio.py` with another `sys.argv` parameter representing one of the three genres.
> 
> @giannamoth can we use the sliders on the left or the buttons in the middle to select the genre? the buttons should return one of the strings in the list above.

Sure, I will do that in the next few days :)
