### ISSUE TITLE
Result page error (CSS missing?)

### ISSUE THREAD

**Issue by giannamoth** [TechLabs-Berlin/wt21-the-noise-enricher#46]
![error2](https://user-images.githubusercontent.com/79792034/151669606-4317fe06-3102-44da-b7cb-b9600ef48d76.PNG)
![error1](https://user-images.githubusercontent.com/79792034/151669611-35d1f981-4883-4e81-a2b7-5d0a2bac4f27.PNG)

I've just pulled the updated Backend from the develop branch, and now I cannot load anymore the result page. SOmehow it looks like the CSS is not present.
Does anyone have the same issue?

**Comment by giannamoth** [comment]
yeah, and it also kicks me out from the server and I have to restart the `nodemon app.js `from the terminal

**Comment by vagechirkov** [comment]
@giannamoth this is super strange because for me everything works just fine!

<details>

![image](https://user-images.githubusercontent.com/42982039/151670544-bdc56ca1-6e02-437c-a4f9-f3859d525c06.png)

![image](https://user-images.githubusercontent.com/42982039/151670597-f32f89a4-7d0c-4092-b092-4c46e5f126d7.png)

</details>

**Comment by vagechirkov** [comment]
@giannamoth  Ahh, I think I know what is the problem! It tries to run the python script on your computer, but you do not have the proper environment! You can replace this [line](https://github.com/TechLabs-Berlin/wt21-the-noise-enricher/blob/fc53e46ee68c9cd32b5037f3198b23dfa3f2061c/node_app/server/controllers/generate-audio.js#L38) from the `generate-audio.js` with the following code:

```javascript

const code = 0;

```

or with this code to test the delay:


```javascript

const code = await new Promise(resolve => setTimeout(resolve, 6000));

```


This should work fine to test spectrograms!

**Comment by vagechirkov** [comment]
@giannamoth Note that you also need to change this [line](https://github.com/TechLabs-Berlin/wt21-the-noise-enricher/blob/fc53e46ee68c9cd32b5037f3198b23dfa3f2061c/node_app/server/controllers/generate-audio.js#L61) to test results downloading

```javascript

const generated_file = "path_to_the_file_in_your_system.wav";


```

**Comment by giannamoth** [comment]
nice! I'm gonna ty this and let you know the results 😎

**Comment by giannamoth** [comment]
OK not it laods the page :D But not the results, it keeps going loading.

**Comment by vagechirkov** [comment]
@giannamoth, I have a better idea. I would suggest replacing `<%= filepath %>` directly in the templates and then updating the `app.js`:


```javascript

app.get('/', (req, res) => {
    res.render('index');
});

app.get('/about', (req, res) => {
    res.render('generate/about');
});

app.get('/generate/spectrogram', (req, res) => {
    res.render('generate/spectrogram');
});
app.get('/generate/results', (req, res) => {
    res.render('generate/results');
});

app.use('/generate', generateRoutes);


``` 


Then you can type in the browser `http://127.0.0.1:3030/generate/results` or `http://127.0.0.1:3030/generate/spectrogram`

**Comment by giannamoth** [comment]
hei valerii, I'm not sure to understand what to do in the second suggestion

**Comment by vagechirkov** [comment]
> hei valerii, I'm not sure to understand what to do in the second suggestion

I mean you can paste here the actual path:

```html

<script>
    const wavesurfer = drawSpectrogram("../../public/uploads/someaudio.wav");

```

This is just for testing.

You can do it [here](https://github.com/TechLabs-Berlin/wt21-the-noise-enricher/blob/27c9d80f65e4c380cb4961418738a75af8adccb0/node_app/client/views/generate/spectrogram.ejs#L32) and [here](https://github.com/TechLabs-Berlin/wt21-the-noise-enricher/blob/27c9d80f65e4c380cb4961418738a75af8adccb0/node_app/client/views/generate/results.ejs#L11)

**Comment by giannamoth** [comment]
`Cannot GET /generate/result`


that is the error message I get

**Comment by vagechirkov** [comment]
> `Cannot GET /generate/result`
> 
> that is the error message I get

Did you change the `app.js`?

**Comment by giannamoth** [comment]
yes

**Comment by giannamoth** [comment]
nevermind
I've pasted the```
 app.get('/generate/spectrogram', (req, res) => {
    res.render('generate/spectrogram');
});
app.get('/generate/results', (req, res) => {
    res.render('generate/results');
});

below the` generateReroutes `and not above
```

**Comment by vagechirkov** [comment]
> nevermind I've pasted the``` app.get('/generate/spectrogram', (req, res) => { res.render('generate/spectrogram'); }); app.get('/generate/results', (req, res) => { res.render('generate/results'); });
> 
> below the`generateReroutes`and not above

You can also put an audio file in the upload folder and set the `app.js` file like this:

```javascript

app.engine('ejs', ejsMate);
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, '/../client/views/'));
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, '/../client')));
app.use(morgan('dev'));

app.get('/', (req, res) => {
    res.render('index');
});

app.get('/generate/spectrogram', (req, res) => {
    res.render('generate/spectrogram', {filepath: "piano_16000_mono.wav"});
});
app.get('/generate/results', (req, res) => {
    res.render('generate/results', {filepath: "piano_16000_mono.wav"});
});

app.get('/about', (req, res) => {
    res.render('generate/about');
});

app.use('/generate', generateRoutes);


```
