### ISSUE TITLE
Generated files

### ISSUE THREAD

**Issue by vagechirkov** [TechLabs-Berlin/wt21-the-noise-enricher#51]
It looks like the generated file is twice shorter as the original one. And it sounds quite different from what I uploaded.

I have deployed the current version with the different styles supported: https://noise-enricher.herokuapp.com/generate

Any ideas? @christian-eismann @RoitRapha

**Comment by christian-eismann** [comment]
@vagechirkov regarding the length issue: maybe your uploaded file has a sampling rate below 22Khz and the up- and downsampling did not work well, leading to a shorter output. i will check that and the other sound issue tonight

**Comment by RoitRapha** [comment]
I can work on this tomorrow morning, if you find anything out @christian-eismann then let me know and I´ll try to continue on it

**Comment by christian-eismann** [comment]
length issue seems to be solved. a loop was missing the last element of a list. however, due to our 3-seconds-restriction: the last audio chunk is always truncated by our network because it does not fit the predefined dimensions. reconstructed audio will always be a bit shorter than the input.

**Comment by vagechirkov** [comment]
@christian-eismann I think the length problem is solved! Do you think the generation works correctly? It sounds a bit... too noisy:))))

Here is the updated version: https://noise-enricher.herokuapp.com/generate
