### ISSUE TITLE
Error while running Nodemon after last merge

### ISSUE THREAD

**Issue by giannamoth** [TechLabs-Berlin/wt21-the-noise-enricher#52]
<img width="1092" alt="Screen Shot 2022-01-31 at 15 27 21" src="https://user-images.githubusercontent.com/79792034/151811498-e18b5315-3e72-4e20-96ca-140720dfc19b.png">
 New fancy error after last merge :(
 
It looks like ios related to the "connect-flash" module. Any idea?

**Comment by vagechirkov** [comment]
@giannamoth Hey, you need to install this module

**Comment by giannamoth** [comment]
gracias :D

**Comment by giannamoth** [comment]
Ach ok I was too quick in closing this. I cannot again load the Spectrogram page. Should I re-do the same workaround (aka replace a few lines of code in `generate-audio.js`) that you have suggested to me before?

**Comment by vagechirkov** [comment]
> Ach ok I was too quick in closing this. I cannot again load the Spectrogram page. Should I re-do the same workaround (aka replace a few lines of code in `generate-audio.js`) that you have suggested to me before?

Yeah, this should work here too! Sorry about that :(
